### PR TITLE
Demo of auto-generated SWIG fortran interfaces to STRUMPACK C interface

### PR DESCRIPTION
**Pull request by sethrj**
This PR demonstrates auto-generated Fortran-2003 interface functions to the existing flat wrappers in `StrumpackSparseSolver.h`. I'll later add object-oriented wrappers based on the underlying C++ code, but this PR is much simpler (a few lines of SWIG) since all the necessary types and declarations are in a single, C-friendly file.

### CODE REVIEW

**Comment by pghysels** [comment]
Thank you! This looks good. It seems quite straightforward.
We need the C interface anyway for other uses, so I think this is a good path forward.
I am going to try this out with an example, and see what needs to be done to integrate it into our build system, documentation etc.

My only issue is that I'm not very happy with the current C interface, which is created manually. 
It has a lot of macro's and passes around void* pointers. It duplicates the C++ scoped enums into different C enums. It always lags behind the C++ code.

I know this might be unrelated to the Fortran interfacing, but are you aware of a more automated way to generate C interfaces from C++ code? Something similar to swig perhaps?

**Comment by pghysels** [comment]
Is this the swig version I need to test this:?
https://github.com/swig-fortran/swig

**Comment by sethrj** [comment]
@pghysels Yes, correct. If you have Spack you can install with `spack install swig@fortran`. I'm going to spend a few minutes right now on the first steps of a real C++ wrapper.

**Comment by sethrj** [comment]
Linking this PR to #28

**Comment by pghysels** [comment]
I have decided to go with the flat interface, based on the C wrapper to the C++ code, for now: https://github.com/pghysels/STRUMPACK/commit/8b6218947edf37aacd4094e989057cdb5cbab743

I'm not familiar enough with Fortran to use the Fortran wrapper generated directly from the C++ code.

I installed swig@fortran through spack.

Thanks!

**Comment by sethrj** [comment]
OK, thanks for the update @pghysels ! Let me know if you or your Fortran users decide to try out  a more "rich" Fortran interface. Cheers!

**Comment by sethrj** [comment]
For reference: the "flat" code in the PR was integrated into master in commit https://github.com/pghysels/STRUMPACK/commit/8b6218947edf37aacd4094e989057cdb5cbab743

**Pull request closed without merging**
