### PR TITLE
Fix compiler warning due to partially overridden `CompressedSparseMatrix::permute`

### PR DESCRIPTION
**Pull request by sebastiangrimberg**
This problem probably popped up only recently since this file is now being installed correctly is my guess.

### CODE REVIEW

**Comment by pghysels** [comment]
Thank you. Indeed some headers were not installed correctly.
I just fixed warning I noticed when compiling with clang, or hipcc: https://github.com/pghysels/STRUMPACK/commit/19d22f7d7c688bd5fecf2751f31d091c396cb225
But I'm not seeing this warning you mention for the permute routine. What compiler are you using?
Perhaps I could also just remove the `virtual` keyword for the `permute` routine taking 2 `vectors`?

**Comment by sebastiangrimberg** [comment]
Thanks for addressing these! These warnings appear when building a file which includes `StrumpackSparseSolverMPIDist.hpp` with `nvcc` using `-Wall -pedantic`. I don't get the warnings when building STRUMPACK likely because the CUDA compilers are only used where necessary. MFEM uses the CUDA compilers everywhere which leads to the issue with `nvcc`.

**Comment by pghysels** [comment]
I see lot's of warnings now when compiling with the NVHPC compilers on Perlmutter.
I will try to fix all these.

**Comment by pghysels** [comment]
I fixed a lot of warnings.
I sometimes still see unused variable warnings, for things that are only used in OpenMP pragmas. I'll fix those later.

**Comment by sebastiangrimberg** [comment]
Awesome! Looks great thanks, I'll close this PR.

**Pull request closed without merging**
